apiVersion: v1
kind: Service
metadata:
  name: todolist-backend-service
  labels:
    app: todolist
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: todolist
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
